# -----------------------------------------------------------------------------
# CppAD: C++ Algorithmic Differentiation: Copyright (C) 2003-18 Bradley M. Bell
#
# CppAD is distributed under multiple licenses. This distribution is under
# the terms of the
#                     Eclipse Public License Version 1.0.
#
# A copy of this license is included in the COPYING file of this distribution.
# Please visit http://www.coin-or.org/CppAD/ for information on other licenses.
# -----------------------------------------------------------------------------
#
sudo:     false
language: cpp
compiler: gcc

script:
    # bin/travis.sh [path_to_one_test]
    # If path_to_one_test is is present, only that test is run,
    # otherwise all the tests are run.
    #
    bin/travis.sh test_more/general/new_dynamic.cpp
