# -----------------------------------------------------------------------------
# CppAD: C++ Algorithmic Differentiation: Copyright (C) 2003-18 Bradley M. Bell
#
# CppAD is distributed under multiple licenses. This distribution is under
# the terms of the
#                     Eclipse Public License Version 1.0.
#
# A copy of this license is included in the COPYING file of this distribution.
# Please visit http://www.coin-or.org/CppAD/ for information on other licenses.
# -----------------------------------------------------------------------------
#
sudo:     false
language: cpp
compiler: gcc

script:
  # bin/travis.sh test_name
  #
  # Where test_name can be 'all', a directory that contains tests,
  # or a file that contains one test. A file that contains one test must
  # have the .cpp extension.  Note that travis does not yet support test
  # that require other packages; e.g., adolc.
  #
  bin/travis.sh all

notifications:
  email:
    recipients:
      bradbell@seanet.com
    on_success: always # default: change
    on_failure: always # default: always
