name: GitHub Actions Demo
on: [push]
jobs:
  learn-actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "github.event.name = ${{ github.event_name }}"
      - run: echo "runner.os = ${{ runner.os }}"
      - run: echo "github.ref = ${{ github.ref }}"
      - run: echo "github.repository = ${{ github.repository }}"
      - run: echo "github.workspace = ${{ github.workspace }}"
      - run: echo "pwd = $(pwd)"
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: echo "The workflow is now ready to test your code on the runner."
      - name: run make check in build subdirectory
        run: |
          mkdir build
          cd build
          random_01=$(expr $RANDOM % 2)
          if [ "$random_01" == '0' ]
          then
            build_type='debug'
          else
            build_type='release'
          fi
          cmake .. -D CMAKE_BUILD_TYPE="$type"
          make -j $(nproc) check
      - run: echo "job.status = ${{ job.status }}"
