name: GitHub Actions Demo
on: [push]
jobs:
  learn-actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "github.event.name = ${{ github.event_name }}"
      - run: echo "runner.os = ${{ runner.os }}"
      - run: echo "github.ref = ${{ github.ref }}"
      - run: echo "github.repository = ${{ github.repository }}"
      - run: echo "github.workspace = ${{ github.workspace }}"
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: echo "The workflow is now ready to test your code on the runner."
      - name: run make check in build subdirectory
        run: |
          mkdir build
          cd build
          set +e
          random_03=$(expr $RANDOM % 4)
          set -e
          if [ "$random_03" == '0' ]
          then
            debug_which='debug_all'
          elif [ "$random_03" == '1' ]
            debug_which='debug_even'
          elif [ "$random_03" == '2' ]
            debug_which='debug_odd'
          else
            debug_which='debug_none'
          fi
          echo "cmake -D cppad_debug_which=$debug_which" ..
          cmake -D cppad_debug_which=$debug_which ..
          echo "make -j $(nproc) check"
          make -j $(nproc) check
      - run: echo "job.status = ${{ job.status }}"
