name: GitHub Actions Demo
on: [push]
jobs:
  learn-actions:
    runs-on: [ ubuntu-latest, macos-latest ]
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: set debug_which
        run: |
          echo "pwd = $(pwd)"
          mkdir build
          cd build
          set +e
          random_03=$(expr $RANDOM % 4)
          set -e
          case $random_03 in
            0) debug_which='debug_all'
            ;;
            1) debug_which='debug_even'
            ;;
            2) debug_which='debug_odd'
            ;;
            3) debug_which='debug_none'
            ;;
          esac
          echo "$debug_which" > debug_which
      - name: run cmake
        run: |
          echo "pwd = $(pwd)"
          cd build
          debug_which=$(cat debug_which)
          echo "cmake -D cppad_debug_which=$debug_which" ..
          # cmake -D cppad_debug_which=$debug_which ..
      - name: run make check
        run: |
          echo "pwd = $(pwd)"
          cd build
          echo "make -j $(nproc) check"
          # make -j $(nproc) check
      - run: echo "job.status = ${{ job.status }}"
