name: GitHub Actions Demo
on: [push]
jobs:
  learn-actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: run cmake
        run: |
          mkdir build
          cd build
          set +e
          random_03=$(expr $RANDOM % 4)
          set -e
          case $random_03 in
            0) debug_which='debug_all'
            ;;
            1) debug_which='debug_even'
            ;;
            2) debug_which='debug_odd'
            ;;
            3) debug_which='debug_none'
            ;;
          esac
          echo "cmake -D cppad_debug_which=$debug_which" ..
          # cmake -D cppad_debug_which=$debug_which ..
          echo "pwd = $(pwd)"
          echo "debug_which=$debug_which"
      - name: Check that pwd and debug_which are the same
        run: |
          echo "pwd = $(pwd)"
          echo "debug_which=$debug_which"
          echo "make -j $(nproc) check"
          # make -j $(nproc) check
      - run: echo "job.status = ${{ job.status }}"
