name: CppAD CI for ubuntu
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name : debug_which
        run: |
          set +e
          random_03=$(expr $RANDOM % 4)
          set -e
          case $random_03 in
            0) debug_which='debug_all'
            ;;
            1) debug_which='debug_even'
            ;;
            2) debug_which='debug_odd'
            ;;
            3) debug_which='debug_none'
            ;;
          esac
          echo "debug_which=$debug_which"
      - name: cmake
        run: |
          mkdir build
          cd build
          echo "cmake -D cppad_debug_which=$debug_which" ..
          cmake -D cppad_debug_which=$debug_which ..
      - name: check
          echo "make -j $(nproc) check"
          make -j $(nproc) check
      - run: echo "job.status = ${{ job.status }}"
